# Generated by Django 3.1 on 2020-09-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_content', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
            ],
        ),
    ]
